filetype plugin indent on
syntax enable
set nocompatible
set modeline
set modelines=5
set nobackup
set nowritebackup
set updatetime=300
set hidden
set noswapfile
set laststatus=2
set shortmess+=c
set clipboard=unnamedplus

let g:markdown_fenced_languages = ['javascript', 'js=javascript', 'json=javascript']

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

call plug#begin()

Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'

call plug#end()

colorscheme dracula

hi Normal ctermbg=black

set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4

set number
set relativenumber
set showcmd
set cmdheight=1
set completeopt=menuone,noinsert,noselect
set splitright
set splitbelow
set ignorecase
set smartcase
set showmatch
set signcolumn=yes
set incsearch
set diffopt+=vertical

" Use ^] to jump to tag under cursor
" Use g^] for ambiguous tags
" Use ^t to jump back up the tag stack
command! MakeTags !ctags -R *

let mapleader="\<space>"

nmap <silent> <c-h> <c-w>h
nmap <silent> <c-j> <c-w>j
nmap <silent> <c-k> <c-w>k
nmap <silent> <c-l> <c-w>l

nmap <leader>Q :bufdo bdelete<CR>

nmap <leader>ve :edit $MYVIMRC<CR>
nmap <leader>vr :source $MYVIMRC <bar> :doautocmd BufRead<CR>

nnoremap <leader>m :MaximizerToggle!<CR>
nnoremap <leader>F :ALEFix<CR>
nnoremap <leader>d :cd %:p:h<CR>:pwd<CR>

vnoremap <c-c> "+y
nnoremap <c-v> "+p

map gf :edit <cfile><CR>

nmap <leader>x :!xdg-open %<CR><CR>
