#!/usr/bin/env bash

while read file
do
    case "$1" in
        "C-d") trash-put "$file" ;;
        "C-c") cat "$file" | xclip -sel c -t image/png ;;
        "C-r") mv "$file" ../rage ;;
        "C-w") xwallpaper --zoom "$file" ;;
    esac
done
