#!/usr/bin/env bash

#if command -v dbus-launch > /dev/null && test -z "${DBUS_SESSION_BUS_ADDRESS}"; then
#	eval $(dbus-launch --sh-syntax --exit-with-session)
#fi

pgrep -x gpg-agent >/dev/null || eval "$(gpg-agent --daemon --allow-preset-passphrase)"
pgrep -x ssh-agent >/dev/null || eval "$(ssh-agent)"

xrandr --addmode HDMI-A-0 1280x960
xrandr --output HDMI-A-0 --mode 1280x960 --primary
xrandr --output DisplayPort-2 --mode 1920x1080 --left-of HDMI-A-0
# xrandr --output DisplayPort-2 --mode 1920x1080 --primary
# xrandr --output HDMI-A-0 --mode 1280x960 --left-of DisplayPort-2

xset r rate 250 30
xset s off -dpms
setxkbmap -option "ctrl:nocaps"
xrdb -merge ~/.Xresources

pgrep -x emacs >/dev/null || /usr/bin/emacs --daemon &
pgrep -x urxvtd >/dev/null || /usr/bin/urxvtd -q -o -f &
pgrep -x pipewire >/dev/null || /usr/bin/pipewire &
pgrep -x mpd >/dev/null || /usr/bin/mpd &
$HOME/.local/bin/set-wallpaper &

exec bspwm
