vim.o.guicursor = 'a:block'
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.signcolumn = 'yes:2'
vim.o.relativenumber = true
vim.o.number = true
vim.o.termguicolors = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.wildmode = 'longest:full,full'
vim.o.wrap = false
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
vim.o.cursorline = 1
vim.o.splitright = 1
vim.o.splitbelow = 1
vim.o.clipboard = 'unnamedplus' -- Use Linux system clipboard
vim.o.updatetime = 250          -- Decrease CursorHold delay
vim.o.redrawtime = 10000        -- Allow more time for loading syntax on large files
vim.o.foldmethod = "expr"
vim.o.foldlevelstart = 10
vim.o.foldexpr = "nvim_treesitter#foldexpr()"
vim.o.hlsearch = 0
