format = """
[](#CA5FCA)\
$username\
[](fg:#CA5FCA bg:#A92BA9 )\
$directory\
[](fg:#A92BA9 bg:#DC317D)\
$git_branch\
$git_status\
[ ](fg:#DC317D)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#CA5FCA"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "fg:#FFFFFF bg:#A92BA9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "fg:#FFFFFF bg:#DC317D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#FFFFFF bg:#DC317D"
format = '[$all_status$ahead_behind ]($style)'
